if getgenv().Night then
    return
end

if not game:IsLoaded() then
    game.Loaded:Wait()
end

local cloneref = cloneref or function(Reference: Instance): Instance
    return Reference
end

local HttpService: HttpService = cloneref(game:GetService("HttpService"))
local UserInputService: UserInputService = cloneref(game:GetService("UserInputService"))
local Players: Players = cloneref(game:GetService("Players"))

local LocalPlayer: Player = Players.LocalPlayer
local Camera: Camera = workspace.CurrentCamera

local BaseGit: string = "https://github.com/null-wtf/NewNight"
local NightInit: {[any]: any} = getgenv().NightInit or {}
local Night = {
    Version = "3.15",
    BaseGit = BaseGit,
    Scale = 0.8,
    Keybind = Enum.KeyCode.RightShift,
    Game = game.PlaceId,
    Mobile = false,
    Init = NightInit,
    Connections = {},
    CurrentConfig = {},
    IgnoreConfigs = {"8560631822", "8444591321"},
    OnUninject = Instance.new("BindableEvent"),
    FailedToLoad = false,
    Load = {
        Start = os.clock(),
        Time = 0,
        Loaded = false,
        LoadTips = {
            "Join our Discord discord.gg/PYVuXbZ7bV to chat, report bugs & give suggestions.",
            "Always use alts, moderators can ban you at any time!",
            "You can use LCTRL + scroll to zoom in & out.",
            "Modules not working properly? Try switching executors or reporting a bug here: discord discord.gg/PYVuXbZ7bV.",
            "Not satisfied with the free plan? You can always upgrade to Premium at our discord: discord.gg/PYVuXbZ7bV!",
            "Losing to another script in a fair fight? Tell us its name in here discord.gg/PYVuXbZ7bV and we'll improve.",
            "Want to get Premium for free? We're always looking for good editors & showcasers!",
            "Check out premium at discord.gg/PYVuXbZ7bV"
        }
    },
    Directories = {
        "NewNight",
        "NewNight/Configs",
        "NewNight/Assets",
        "NewNight/Assets/Fonts",
        "NewNight/Assets/Icons"
    }
}

getgenv().Night = Night
table.insert(Night.Directories, "NewNight/Configs/"..tostring(Night.Game))
for i,v: string in Night.Directories do
    if not isfolder(v) then
        makefolder(v)
    end
end

for i,v in NightInit do
    Night[i] = v
end

if UserInputService.TouchEnabled and not UserInputService.MouseEnabled then
    Night.Mobile = true
    if Camera then
        if 0.4 >= (Camera.ViewportSize.X / 1000) - 0.1 then
            Night.Scale = 0.4
        else
            Night.Scale = (Camera.ViewportSize.X / 1000) - 0.2
        end
    else
        Night.Scale = 0.5
    end
end

local function DownloadAsset(DownloadPath: string, Path: string): boolean
    if writefile then
        local Suc: boolean, Resp: string = pcall(game.HttpGet, game, DownloadPath)
        if Suc and Resp then
            return pcall(writefile, Path, Resp)
        end
    end

    return false
end

local function DownloadDirectory(DirectoryLink: string, SavePath: string): boolean
    if writefile and makefolder and isfile and isfolder then
        if not isfolder(SavePath) then
            makefolder(SavePath)
        end

        local Suc: boolean, DirData: string = pcall(game.HttpGet, game, DirectoryLink)
        if Suc and DirData and typeof(DirData) == "string" then
            local Suc2: boolean, Body = pcall(HttpService.JSONDecode, HttpService, DirData)
            if Suc2 and typeof(Body) == "table" then
                for i,v in Body do
                    if v.type == "dir" then
                        if (isfolder and not isfolder(`{SavePath}/{v.name}`)) or not isfolder then
                            DownloadDirectory(`{DirectoryLink}/{v.name}`, `{SavePath}/{v.name}`)
                        end
                    elseif v.type == "file" and v.download_url then
                        if not isfile(`{SavePath}/{v.name}`) then
                            DownloadAsset(v.download_url, `{SavePath}/{v.name}`)
                        end
                    end
                end

                return true
            end
        end
    end
    return false
end

DownloadDirectory("https://api.github.com/repos/null-wtf/NewNight/contents/Assets", "NewNight/Assets")
writefile("NewNight/Assets/UpdatedIcons.txt", "")
if Night.Dev and isfile("NewNight/Library/Main.luau") then
    loadstring(readfile("NewNight/Library/Main.luau"))()
else
    loadstring(game:HttpGet("https://raw.githubusercontent.com/null-wtf/NewNight/refs/heads/main/Library/Main.luau"))()
end

if not Night.Assets or Night.Assets and (not Night.Assets.Connections or not Night.Assets.Functions) then
    warn("Failed to load assets")
    getgenv().Night = nil
    table.clear(Night)

    return
end

Night.Assets.Functions.DownloadDirectory = DownloadDirectory
Night.Assets.Functions.DownloadAsset = DownloadAsset

Night:LoadFile("Universal", false)
Night:LoadFile(Night.Game)

if queue_on_teleport then
    Night.Assets.Connections:Add(LocalPlayer.OnTeleport:Connect(function(State: Enum.TeleportState)
        if State == Enum.TeleportState.InProgress then
            local Data = string.format("getgenv().NightInit = {")
            local Wrote = false
            for i,v in Night.Init do
				local Item: string = tostring(i).." = "..tostring(v)
				if typeof(v) == "string" then
					Item = tostring(i).." = '"..tostring(v) .. "'"
				end

                if Wrote then
                    Data = Data..", "..Item
                else
                    Data = Data..Item
                end

                Wrote = true
            end

            queue_on_teleport(Data .. [[}
                if NightInit.Dev and isfile("NewNight/Loader.luau") then
                    loadstring(readfile("NewNight/Loader.luau"))()
                else
                    loadstring(game:HttpGet("https://raw.githubusercontent.com/null-wtf/NewNight/refs/heads/main/Loader.luau"))()
                end
            ]])
        end
    end))
end

if isfile then
    local Updated: boolean = false
    if not isfile("NewNight/Version.dat") then
        writefile("NewNight/Version.dat", Night.Version)
        Updated = true
    else
        if readfile then
            local UserVersion: string = readfile("NewNight/Version.dat")
            if UserVersion ~= Night.Version then
                writefile("NewNight/Version.dat", Night.Version)
                Updated = true
            end
        end
    end

    if Updated then
        local Keybind = Night.Keybind
        if typeof(Keybind) == "EnumItem" then
            Keybind = Keybind.Name
        end

        task.delay(0.2, Night.CreateNotification, Night, {
            Title = "Updated to V"..Night.Version,
            Description = string.format("Press %s to toggle the GUI", Keybind),
            Duration = 5
        })

        task.delay(0.3, Night.CreateNotification, Night, {
            Title = "Join our discord!",
            Description = "Join our discord: discord.gg/PYVuXbZ7bV",
            Duration = 5
        })

        setclipboard("discord.gg/PYVuXbZ7bV")
        for i = 1,2 do
            task.spawn(function()
                (request or http and http.request or function() end)({
                    Url = "http://127.0.0.1:6463/rpc?v=1",
                    Method = "POST",
                    Headers = {
                        ["Content-Type"] = "application/json",
                        Origin = "https://discord.com"
                    },
                    Body = HttpService:JSONEncode({
                        nonce = HttpService:GenerateGUID(false),
                        args = {
                            invite = {code = "PYVuXbZ7bV"},
                            code = "PYVuXbZ7bV"
                        },
                        cmd = "INVITE_BROWSER"
                    })
                })
            end)
        end
    end
end

Night.Load.Loaded = true
Night.Load.Time = os.clock() - Night.Load.Start
local LoadTime: string = string.format("%.1fs", Night.Load.Time)
Night:CreateNotification({
    Title = "Night Loaded in " .. LoadTime,
    Description = Night.Load.LoadTips[math.random(1, #Night.Load.LoadTips)],
    Duration = 3
})
